# Example settings file
# Src should always be an absolute path
# But in the example it will be compiled

symlink:
  - title: Symlink Example
    src: ./src/example.txt
    dst: ./dst/example.symlink.txt

hardlink:
  - title: Hardlink Example
    src: ./src/example.txt
    dst: ./dst/example.hardlink.txt

copy:
  - title: Copy Example
    src: ./src/example.txt
    dst: ./dst/example.copy.txt

hardlink:
  - title: Hardlink Example
    src: ./src/example.txt
    dst: ./dst/example.hardlink.txt
